accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views
app_name= 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('change-password', auth_views.PasswordChangeView.as_view(template_name='accounts/change_password.html', success_url=reverse_lazy("queue_management:update-queue")), name='change-password'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

queue_management/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name= 'queue_management'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='queue'),
    path('update-queue/',views.CheckOutNumberView.as_view() , name='update-queue'),
    path('free-queue/',views.FreeCheckOutView.as_view() , name='free-queue'),
]

weiti/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('',include('queue_management.urls', namespace='queue_management')),
    path('login-succes/',views.LogInView.as_view(), name='success-login'),
    path('logout-succes/',views.LogOutView.as_view(), name='success-logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

queue_management/models.py
from django.db import models

# Create your models here.

queue_management/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class CheckOutNumberForm(forms.Form):
    check_out_number = forms.IntegerField(validators=[MinValueValidator(1)], label="Check out number")
class FreeCheckOutForm(forms.Form):
    pass

accounts/views.py
from django.shortcuts import render

queue_management/views.py
from django.shortcuts import render
from .forms import FreeCheckOutForm, CheckOutNumberForm
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
import redis
r = redis.Redis(host='localhost', port=32743, charset="utf-8", decode_responses=True, db=0)

class CheckOutNumberView(LoginRequiredMixin, FormView):
    template_name = 'queue_management/update-queue.html'
    form_class = CheckOutNumberForm
    success_url = reverse_lazy('queue_management:free-queue')

    def form_valid(self, form):
        #print("This is a form {}".format(type(form.cleaned_data["check_out_number"])))
        user=str(self.request.user)
        print(user)
        r.set("user:"+user, form.cleaned_data["check_out_number"])
        return super().form_valid(form)

class FreeCheckOutView(LoginRequiredMixin, FormView):
    template_name = 'queue_management/free-queue.html'
    form_class = FreeCheckOutForm
    success_url = reverse_lazy('queue_management:free-queue')

    def form_valid(self, form):
        #print("This is a form {}".format(type(form.cleaned_data["check_out_number"])))
        user=str(self.request.user)
        number=int(r.get("user:"+user))
        r.lpush("free-checkout", number)
        return super().form_valid(form)

class HomePageView(TemplateView):

    template_name = "queue_management/queue.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        check_out_number=r.rpop("free-checkout")

        if check_out_number == None:
            context['check_out_number'] = "Espere, en breve se le asignará una caja "
        else:
            context['check_out_number'] = "Dirijase a la caja numero: "+str(check_out_number)
        return context

weiti/views.py
from django.views.generic import TemplateView

class LogInView(TemplateView):
    template_name='success_login.html'

class LogOutView(TemplateView):
    template_name='success_logout.html'

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
  <h2>{{ user.username}}</h2>
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}

  <h1>Log In</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Log In" class='btn btn-default'>
    <input type="hidden" name="next" value="{% url 'queue_management:update-queue' %}">
  </form>
{% endblock %}

queue_management/templates/queue_management/free-queue.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
  {% csrf_token %}
  {{form}}
  <button type="submit">I'm Free</button>
</form>
<a class="navbar-brand" href="{%url 'queue_management:update-queue' %}">Change CheckOut</a>
{% endblock %}

queue_management/templates/queue_management/queue.html
{% extends 'base.html' %}
{% block content %}
<h1 class="checkout"> {{check_out_number}}</h1>
{% endblock %}

queue_management/templates/queue_management/update-queue.html
{% extends 'base.html' %}
{% block content %}
<form  method="post">
  {% csrf_token %}
  {{form}}
  <button type="submit">Submit</button>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles%}
<html>
  <head>
    <meta charset="utf-8">
    <title>U-events</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{%url 'queue_management:queue' %}">Queue</a>
        <ul class="navbar-nav justify-content-end">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'accounts:logout'%}">Log Out</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change-password' %}">Change Passwords</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'queue_management:free-queue'%}">Queue Management</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'admin:index'%}">Admin</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container content">
      {% block content %}
      {% endblock %}
    </div>



  </body>
</html>

templates/success_login.html
{%extends 'base.html'%}
{% block content %}
  {% if user.is_authenticated %}
    <h1>Bienvenido {{user.username}}</h1>
  {%else %}
    <h1>Error</h1>
  {%endif%}
{% endblock %}

templates/success_logout.html
{%extends 'base.html'%}
{% block content %}

    <h1>Nos vemos pronto</h1>

{% endblock %}